### ISSUE TITLE
Batocera game resolution scaling problems

### ISSUE THREAD

**Issue by beastieboy** [ChokoGroup/CHA-Multi-OS-Boot#1]
The only thing that currently fails is screen shrinking in vertical games in FBNeo, for example Arcanoid2. The games are playable but only a fraction of screen is displayed. I tested in Batocera 1080i. In version 1.1 (Barocera 33) the problem is not present.

**Comment by cjom** [comment]
This was confirmed to be a Batocera 34 issue and fortunately is fixed in Batocera 35.
We have now new system images with Batocera 35 released.
